### PR TITLE
Merge in latest from datadog/dd-trace-py

### PR DESCRIPTION
**Pull request by brettlangdon**
https://github.com/DataDog/dd-trace-py/commit/1e87c9bdf7769032982349c4ccc0e1c2e6866a16

### CODE REVIEW

**Comment by Oberon00** [comment]
> For a PR to pass, each commit must pass this check: the Github user that the commit is attributed to (based on a match between the commit authorship and Github profile) must be linked to a Linux Foundation ID user

I assume, since this PR contains commits by many users, all of them need to sign the CLA.

**Comment by brettlangdon** [comment]
I signed the CLA

**Comment by tedsuo** [comment]
Hi @brettlangdon. After some debate in the Python SIG, we've decided to take a slightly different approach. We're still very interested in this donation - especially the instrumentation. But, rather than start from one repo and modify the pieces in-place to match OpenTelemetry, we would like the PRs to have already modified the individual pieces. This will allow us to take donations from multiple sources, and avoid having to track down the other 20+ individuals who would also need so sign the CLA as part of this donation.

We'd like our auto-instrumentation story broken into two parts. The first part is the auto-installer, containing the core components for installing the SDK, plugins, and instrumentation packages.

The second part is each individual plugin and instrumentation package. Most of them will likely live in a python-contrib package for now, and the rest in 3rd-party repos. 

The technical details of the approach we would like to take can be found here. It is very similar to Datadog's approach, with some additional details. We would appreciate a review of this document, if you have the time: https://gist.github.com/ocelotl/bf7bfcbb407b995280b6ef48c3870015

Apologies for the change of plans after you already made the PR - the surprise CLA requirement was kind of a doozy. Again, we really appreciate this work being provided from Datadog. We're hoping that an expert in python auto-instrumentation (possibly you?) would still be available to advise and assist us with building auto-installation for OpenTelemetry.

Please let me know if you have any questions. Once this PR is resolved, we will delete this repo and begin porting components to the main https://github.com/open-telemetry/opentelemetry-python repo.

Thank you,
@tedsuo

**Comment by tedsuo** [comment]
Glad to see the CLA issues resolved. @codeboten this LGTM.

**Pull request merged**
